// Digest golden-vector constants for the DEBT-04 cross-runtime parity gate.
//
// WR-15 (17-REVIEW): this file is the SINGLE SOURCE OF TRUTH for the golden
// vectors. It lives in src/ (not test/) so both consumers import the same
// module and can never drift:
//   - packages/vote-engine/test/fixtures/digest-vectors.ts re-exports it for
//     the Node-side digest-parity spec.
//   - apps/VoteTorrentAuthority/src/engines/persistence-proof.ts imports it
//     via `@votetorrent/vote-engine/rn` for the device-side parity gate
//     (assertDigestParity).
// Do NOT inline copies of these vectors anywhere else.
//
// Each vector describes a set of args, the expected base64url SHA-256 output
// from the `Digest()` SQL scalar registered in `database/initialize.ts`, and
// a human-readable label.
//
// Phase 29 (SIGN-05): Semantics follow the canonical injective implementation
// in @optimystic/quereus-plugin-crypto@^0.14.0 — length-prefixed, type-tagged
// encoding (`encodeFields`) before hashing. This replaces the old `|`-join
// semantics. Key properties:
//   - NULL encodes as a bare 0x00 tag (DISTINCT from empty string)
//   - integers encode with TAG_INT (0x01), distinct from TEXT '123' (TAG_TEXT 0x03)
//   - delimiter characters in a field payload do NOT affect framing (length-prefixed)
//
// The expected values were generated by running the LIVE registered Digest()
// SQL function against a prepareDb-initialized Database instance:
//   const db = new Database()
//   await prepareDb(db)  // registers plugin with { algorithm:'sha256', encoding:'base64url' }
//   const row = await db.prepare('select Digest(:a0, :a1) as d').get({ a0, a1 })
// This is the D-02 single-source requirement: NO independent createHash
// reimplementation — the expected values come from the same code path that
// the schema constraints use at runtime.
//
// NOTE on int-arg vs string-int vectors (SIGN-05 fix):
//   The canonical encoding applies type tags — TAG_INT (0x01) for integers and
//   TAG_TEXT (0x03) for text. Therefore Digest(1, 'a') and Digest('1', 'a')
//   produce DIFFERENT hashes. This is a deliberate improvement: the old |‐join
//   UDF coerced both to '1' via String(), producing equal outputs (the SIGN-05
//   collision class). Both vectors are retained and their `expected` values now
//   DIFFER from each other, proving injectivity is enforced.

export interface DigestVector {
  label: string
  args: Array<string | number | null>
  /** Precomputed base64url SHA-256 of canonical length-prefixed, type-tagged encoding of args. */
  expected: string
}

export const DIGEST_VECTORS: DigestVector[] = [
  // Single string arg
  {
    label: 'single-string',
    args: ['hello'],
    expected: 'jGPLAf-oSRaO_ruhnLpaMN9hDaHeTHZczsC2cd4h5zE',
  },
  // Multiple string args (length-prefixed — no delimiter needed)
  {
    label: 'multi-arg',
    args: ['foo', 'bar', 'baz'],
    expected: 'SG4DIH_rRvsqnvHCPB6gtB9EV8SpYgRBChA1EjrstjQ',
  },
  // Null in the middle — encodes as bare 0x00 (DISTINCT from empty string)
  {
    label: 'null-arg',
    args: ['a', null, 'b'],
    expected: 'hecucNQMQdMlUXANcUPVjKV3SxpR-GKE8YLUyfuvwAI',
  },
  // Unicode multi-byte characters
  {
    label: 'unicode',
    args: ['votetorrent', 'ÿ'],
    expected: '0kdcC0wPGUjDGriHkYJCEp40rxZ7Jz2raGYgDYjXStA',
  },
  // Integer 1 (TAG_INT 0x01) — DISTINCT from string '1' (TAG_TEXT 0x03)
  {
    label: 'int-arg',
    args: [1, 'a'],
    expected: 'RzAWhDmX8NV888qpG4NrEyq4O7bQevDfx66Ao-KqH00',
  },
  // String '1' (TAG_TEXT 0x03) — DISTINCT from integer 1 (TAG_INT 0x01)
  {
    label: 'string-int',
    args: ['1', 'a'],
    expected: 'zhDoBFB8FqSzDf_cjS-nlhGaYJVRJJLuPsqA-0XsnjE',
  },
  // SC2 collision vector: delimiter in payload — 'a|b','c' MUST differ from 'a','b|c'
  // (length-prefixed encoding means the 2 vs 3 char first-field lengths diverge)
  {
    label: 'collision-delimiter-split',
    args: ['a|b', 'c'],
    expected: 'tL3oCVCiT3wM-5Y1ScwEGYuQYTdmPtzNR_Qy4pjH25I',
  },
  {
    label: 'collision-delimiter-split-2',
    args: ['a', 'b|c'],
    expected: 'LR1kky-wa0_keSXSVjLx2T90fCwO9WFFiWA5W33nGQQ',
  },
  // SC2 collision vector: NULL vs empty string — 0x00 vs TAG_TEXT 0x03 0x00
  {
    label: 'null-vs-empty',
    args: ['x', null],
    expected: '9lnSk8d91RZiXdT2uwf2AYQTe3GEuBdLZprFRr1Z69k',
  },
  {
    label: 'null-vs-empty-2',
    args: ['x', ''],
    expected: 'FIGG288mRxydQYLg3PKG8EANLLRaVl1ZsKr33NP2rQA',
  },
]
